#!/usr/bin/env bash
# Deploy tools
# this script generates a docker-compose.yml.
#
# example: ./deploy
# example: ./deploy --skip-update
#
# Mostly of scripts fork from https://github.com/getsentry/onpremise
# Original License: https://github.com/getsentry/onpremise/blob/master/LICENSE

source "$(dirname $0)/scripts/function.sh"

# Prepare
source "scripts/load-cli-parser.sh"
source "scripts/error-handling.sh"
source "scripts/check-requirements.sh"

# Core
source "scripts/generate-env-file.sh"
source "scripts/generate-secret-key.sh"
source "scripts/generate-domain.sh"
source "scripts/configure-cert.sh"
source "scripts/generate-compose-file.sh"
source "scripts/configure-volumes.sh"
source "scripts/fetch-docker-images.sh"
source "scripts/turn-things-off.sh"
source "scripts/wrap-up.sh"
