#!/usr/bin/env bash
# Upgrade tools
# Upgrade zealot to run
#
# example: ./upgrade

set -e

stop_docker_compose () {
  docker-compose down &> /dev/null
}

download_docker_images () {
  echo ""
  echo "== Pulling Docker images =="
  docker-compose pull
  echo "Docker images pulled."
}

upgrade_database () {
  echo ""
  echo "== Upgrading database =="
  docker-compose run --rm zealot run_upgrade
}

all_done () {
  echo ""
  echo "== All done =="
  echo ""
  echo "Run the following command get Zealot running:"
  echo ""
  echo "  docker-compose up -d"
  echo ""
}


stop_docker_compose
download_docker_images
upgrade_database
all_done
