#!/usr/bin/env bash
# Upgrade tools
# Upgrade zealot to run
#
# example: ./upgrade

set -e

stop_docker_compose () {
  docker-compose down &> /dev/null
}

remove_unused_docker_volumes () {
  echo ""
  echo "== Deleting zealot-app volume =="

  # always remove zealot-app volume to make sure use old zealot data
  HAS_APP_VOLUME=$(docker volume ls | grep -v DRIVER | grep zealot-app | wc -l 2> /dev/null)
  if [ -z "$HAS_APP_VOLUME" ]; then
    docker volume rm zealot-app
  fi
}

download_docker_images () {
  echo ""
  echo "== Pulling Docker images =="
  docker-compose pull
  echo "Docker images pulled."
}

upgrade_database () {
  echo ""
  echo "== Upgrading database =="
  docker-compose run --rm zealot run_upgrade
}

all_done () {
  echo ""
  echo "== All done =="
  echo ""
  echo "Run the following command get Zealot running:"
  echo ""
  echo "  docker-compose up -d"
  echo ""
}


stop_docker_compose
remove_unused_docker_volumes
download_docker_images
upgrade_database
all_done
